apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aurum-api
  namespace: aurum-dev
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: api
  namespaceSelector:
    matchNames:
      - aurum-dev
  endpoints:
    - interval: 30s
      port: http
      path: /metrics
