version: 2

sources:
  - name: iceberg_raw
    description: Iceberg raw landing tables populated by ingestion jobs.
    schema: raw
    freshness:
      warn_after: {count: 6, period: hour}
      error_after: {count: 12, period: hour}
    tables:
      - name: curve_landing
        description: Landing table written directly by ingestion jobs (includes quarantine reason).
        loaded_at_field: _ingest_ts
        columns:
          - name: curve_key
            tests:
              - not_null
          - name: quarantine_reason
            description: Reason assigned when a row fails validation.
  - name: iceberg_market
    description: Iceberg curated market tables.
    schema: market
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: curve_observation
        description: Canonical Iceberg table containing normalized vendor curve rows.
        loaded_at_field: _ingest_ts
        columns:
          - name: curve_key
            tests:
              - not_null
          - name: _ingest_ts
            tests:
              - not_null
      - name: curve_observation_quarantine
        description: Repository of quarantined rows awaiting remediation.
        loaded_at_field: _ingest_ts
        columns:
          - name: quarantine_reason
            tests:
              - not_null
      - name: scenario_output
        description: Scenario engine outputs appended by the worker.
        loaded_at_field: _ingest_ts
        columns:
          - name: scenario_id
            tests:
              - not_null
          - name: tenant_id
            tests:
              - not_null
          - name: run_id
            tests:
              - not_null
          - name: metric
            tests:
              - not_null
          - name: _ingest_ts
            tests:
              - not_null

models:
  - name: stg_curve_landing
    description: Staging model that normalizes landing rows and retains quarantine context.
    columns:
      - name: currency
        tests:
          - not_null
      - name: per_unit
        tests:
          - not_null
  - name: stg_curve_quarantine
    description: Filtered view of landing rows that were quarantined with reasons attached.
    columns:
      - name: quarantine_reason
        tests:
          - not_null
  - name: stg_curve_observation
    description: Staging model that harmonizes curve observations for downstream consumption.
    columns:
      - name: curve_key
        tests:
          - not_null
      - name: tenor_label
        tests:
          - not_null
      - name: currency
        description: Normalized currency code for the curve price.
      - name: per_unit
        description: Normalized unit denominator for the curve price.
  - name: publish_curve_observation
    description: Incremental publish step that materializes the canonical curve table from landing data.
    tests:
      - unique:
          column_name: "curve_key || '|' || tenor_label || '|' || cast(asof_date as varchar)"
  - name: int_curve_monthly
    description: Intermediate model filtering to monthly tenors and latest copies per ingest.
    tests:
      - unique:
          column_name: "curve_key || '|' || tenor_label || '|' || cast(asof_date as varchar)"
    columns:
      - name: asof_date
        tests:
          - not_null
      - name: currency
        description: Currency propagated from the staging model.
      - name: per_unit
        description: Unit denominator propagated from the staging model.
  - name: mart_curve_latest
    description: Business mart exposing the latest available curve per identity and tenor.
    tests:
      - unique:
          column_name: "curve_key || '|' || tenor_label"
    columns:
      - name: mid
        tests:
          - not_null
      - name: currency
        description: Currency associated with the curve mid price.
      - name: per_unit
        description: Unit denominator associated with the curve mid price.
  - name: int_curve_calendar
    description: Calendar strips derived by averaging monthly curves.
    tests:
      - unique:
          column_name: "curve_key || '|' || tenor_label || '|' || cast(asof_date as varchar)"
    columns:
      - name: asof_date
        tests:
          - not_null
      - name: tenor_type
        tests:
          - accepted_values:
              values: ['CALENDAR']
      - name: mid
        tests:
          - not_null
  - name: int_curve_quarter
    description: Quarterly strips derived by averaging monthly curves.
    tests:
      - unique:
          column_name: "curve_key || '|' || tenor_label || '|' || cast(asof_date as varchar)"
    columns:
      - name: asof_date
        tests:
          - not_null
      - name: tenor_type
        tests:
          - accepted_values:
              values: ['QUARTER']
      - name: mid
        tests:
          - not_null
  - name: mart_scenario_output
    description: Latest scenario outputs materialized as a Trino view.
    tests:
      - unique:
          column_name: "tenant_id || '|' || scenario_id || '|' || run_id || '|' || metric || '|' || tenor_label"
    columns:
      - name: scenario_id
        tests:
          - not_null
      - name: run_id
        description: Identifier of the scenario run that produced the output.
        tests:
          - not_null
      - name: tenant_id
        tests:
          - not_null
      - name: value
        tests:
          - not_null
      - name: metric_currency
        description: Currency code parsed from the metric unit metadata.
      - name: metric_unit_denominator
        description: Unit denominator parsed from the metric unit metadata (e.g., MWh).
  - name: mart_scenario_metric_latest
    description: Helper view exposing the latest value per scenario and metric.
    tests:
      - unique:
          column_name: "tenant_id || '|' || scenario_id || '|' || metric"
    columns:
      - name: scenario_id
        tests:
          - not_null
      - name: run_id
        description: Run identifier corresponding to the latest metric value.
        tests:
          - not_null
      - name: tenant_id
        tests:
          - not_null
      - name: metric
        tests:
          - not_null
      - name: latest_value
        description: Most recent value for the metric.
      - name: latest_asof_date
        description: As-of date associated with the latest metric value.
  - name: mart_ppa_valuation
    description: Persisted PPA valuation cashflows and summary metrics.
    tests:
      - unique:
          column_name: "ppa_contract_id || '|' || scenario_id || '|' || metric || '|' || coalesce(cast(period_start as varchar), '')"
    columns:
      - name: ppa_contract_id
        tests:
          - not_null
      - name: scenario_id
        tests:
          - not_null
      - name: metric
        tests:
          - not_null

exposures:
  - name: scenario_outputs_mart
    type: dashboard
    maturity: medium
    url: https://internal.aurum.local/dashboards/scenario
    depends_on:
      - ref('mart_scenario_output')
      - ref('mart_scenario_metric_latest')
    owner:
      name: Scenario Analytics
      email: analytics@aurum.local
  - name: iceberg_maintenance
    type: application
    maturity: low
    url: https://airflow.aurum.local/dag/iceberg_maintenance
    description: Scheduled job that expires Iceberg snapshots and compacts data files.
    depends_on:
      - source('iceberg_market', 'curve_observation')
      - source('iceberg_market', 'scenario_output')
    owner:
      name: Platform Operations
      email: platform@aurum.local
