apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aurum-dev
resources:
  - ../base
  - ../ui

patchesStrategicMerge:
  - patches/api-vault.yaml
  - patches/scenario-worker-vault.yaml
  - patches/deployment-tolerations.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: aurum-secrets
    namespace: aurum-dev
    behavior: merge
    literals:
      - POSTGRES_DB=aurum
      - POSTGRES_USER=aurum
      - POSTGRES_PASSWORD=aurum123
      - REDIS_PASSWORD=aurum123
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
