apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurum-api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            cpu: 300m
            memory: 768Mi
          limits:
            cpu: "1.5"
            memory: 1.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurum-scenario-worker
spec:
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            cpu: 400m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
