name: "aurum"
version: "1.1.0"
config-version: 2
profile: "aurum"

model-paths: ["dbt/models"]
macro-paths: ["dbt/macros"]
seed-paths: ["dbt/seeds"]
snapshot-paths: ["dbt/snapshots"]
analysis-paths: ["dbt/analysis"]
target-path: "artifacts/dbt/target"
clean-targets:
  - "artifacts/dbt/target"
  - "artifacts/dbt/dbt_packages"

models:
  aurum:
    +materialized: view
    stg:
      +schema: stg
    int:
      +schema: int
    marts:
      +schema: mart

seeds:
  aurum:
    ref:
      +schema: ref
    raw:
      +schema: raw
    market:
      +schema: market_seed
    timescale:
      +schema: public
      +database: "{{ 'timeseries' if target.name != 'duckdb' else (target.database if target.database else 'main') }}"
    environment:
      +schema: environment
