kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: aurum-dev
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30443
    hostPort: 8443
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 32080
    hostPort: 32080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 32443
    hostPort: 32443
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30808
    hostPort: 8080
    listenAddress: "127.0.0.1"
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
