{{ config(materialized='view') }}

with source_data as (
    select
        asof_date,
        source_file,
        sheet_name,
        asset_class,
        region,
        iso,
        location,
        market,
        product,
        block,
        spark_location,
        price_type,
        units_raw,
        upper(nullif(currency, '')) as currency,
        upper(nullif(per_unit, '')) as per_unit,
        tenor_type,
        cast(contract_month as date) as contract_month,
        tenor_label,
        value,
        bid,
        ask,
        mid,
        curve_key,
        version_hash,
        cast(_ingest_ts as timestamp) as _ingest_ts,
        quarantine_reason
    from {{ source('iceberg_raw', 'curve_landing') }}
)
select
    asof_date,
    source_file,
    sheet_name,
    asset_class,
    region,
    iso,
    location,
    market,
    product,
    block,
    spark_location,
    price_type,
    units_raw,
    currency,
    per_unit,
    tenor_type,
    contract_month,
    tenor_label,
    value,
    bid,
    ask,
    coalesce(mid, value) as mid,
    curve_key,
    version_hash,
    _ingest_ts,
    quarantine_reason
from source_data
