apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-alerts
  namespace: monitoring
data:
  backup-alerts.yml: |
    groups:
      - name: backup_alerts
        rules:
          - alert: BackupJobFailed
            expr: kube_job_status_failed{job_name=~"(postgres|timescale|clickhouse|minio|kafka|vault)-backup"} > 0
            for: 5m
            labels:
              severity: critical
              service: backup
            annotations:
              summary: "Backup job failed for {{ $labels.job_name }}"
              description: "Backup job {{ $labels.job_name }} has failed. Check backup logs and retry manually."
              runbook: "https://github.com/aurum/aurum-platform/blob/main/docs/backup-recovery.md#troubleshooting"

          - alert: BackupValidationFailed
            expr: kube_job_status_failed{job_name="backup-validation"} > 0
            for: 5m
            labels:
              severity: critical
              service: backup
            annotations:
              summary: "Backup validation failed"
              description: "Backup validation job has failed. Some backups may be corrupted or missing."
              runbook: "https://github.com/aurum/aurum-platform/blob/main/docs/backup-recovery.md#backup-validation"

          - alert: NoRecentBackup
            expr: |
              time() - kube_job_status_completion_time{job_name=~"(postgres|timescale|clickhouse|minio|kafka|vault)-backup"} > 86400
            for: 10m
            labels:
              severity: warning
              service: backup
            annotations:
              summary: "No recent backup for {{ $labels.job_name }}"
              description: "No successful backup in the last 24 hours for {{ $labels.job_name }}. Check backup job scheduling."

          - alert: BackupTooOld
            expr: |
              time() - kube_job_status_completion_time{job_name=~"(postgres|timescale|clickhouse|minio|kafka|vault)-backup"} > 172800
            for: 10m
            labels:
              severity: critical
              service: backup
            annotations:
              summary: "Backup too old for {{ $labels.job_name }}"
              description: "Last successful backup for {{ $labels.job_name }} is more than 48 hours old. Immediate attention required."

          - alert: BackupJobRunningTooLong
            expr: |
              kube_job_status_active{job_name=~"(postgres|timescale|clickhouse|minio|kafka|vault)-backup"} * on(job_name) group_left kube_job_status_start_time > 7200
            for: 5m
            labels:
              severity: warning
              service: backup
            annotations:
              summary: "Backup job running too long"
              description: "Backup job {{ $labels.job_name }} has been running for more than 2 hours."

          - alert: BackupStorageFull
            expr: |
              (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~"backup-.*"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"backup-.*"}) * 100 < 10
            for: 5m
            labels:
              severity: critical
              service: storage
            annotations:
              summary: "Backup storage running low"
              description: "Backup storage has less than 10% space remaining."

          - alert: RestoreJobFailed
            expr: kube_job_status_failed{job_name=~"(postgres|timescale|clickhouse|minio|kafka|vault)-restore"} > 0
            for: 0m
            labels:
              severity: critical
              service: recovery
            annotations:
              summary: "Restore job failed"
              description: "Restore job {{ $labels.job_name }} has failed. Check restore logs and manual intervention may be required."

          - alert: DataStoreUnavailable
            expr: |
              up{job=~"postgres|timescale|clickhouse|minio|kafka|vault"} == 0
            for: 5m
            labels:
              severity: critical
              service: datastore
            annotations:
              summary: "Data store unavailable"
              description: "{{ $labels.job }} service is down. Check service status and logs."

      - name: backup_metrics
        rules:
          - record: backup:success_rate_24h
            expr: |
              sum(rate(kube_job_status_succeeded{job_name=~".*-backup"}[24h])) / sum(rate(kube_job_status_created{job_name=~".*-backup"}[24h]))

          - record: backup:latest_age_hours
            expr: |
              (time() - kube_job_status_completion_time{job_name=~".*-backup"}) / 3600

          - record: backup:total_size_bytes
            expr: |
              sum(kube_job_status_succeeded{job_name=~".*-backup"}) * on(job_name) group_left kube_job_info

          - record: recovery:time_seconds
            expr: |
              kube_job_status_completion_time{job_name=~".*-restore"} - kube_job_status_start_time{job_name=~".*-restore"}
