apiVersion: v1
kind: ConfigMap
metadata:
  name: preview-environment-config
  labels:
    app.kubernetes.io/instance: aurum-preview
    app.kubernetes.io/name: aurum-preview
    app.kubernetes.io/component: preview-environment
data:
  PREVIEW_MODE: "true"
  DEBUG_MODE: "true"
  LOG_LEVEL: "DEBUG"
  AURUM_ENVIRONMENT: "preview"
  AURUM_PREVIEW_PR_NUMBER: ""
  AURUM_PREVIEW_BRANCH: ""
  AURUM_PREVIEW_COMMIT: ""
  # Preview-specific configuration
  AURUM_API_RATE_LIMIT_RPS: "5"  # Reduced rate limit for preview
  AURUM_API_RATE_LIMIT_BURST: "10"
  AURUM_API_CACHE_TTL: "30"  # Shorter cache TTL for preview
  AURUM_API_INMEMORY_TTL: "15"
  # Preview database configuration
  AURUM_APP_DB_DSN: "postgresql://aurum:aurum@postgres-preview.aurum-dev.svc.cluster.local:5432/aurum_preview"
  # Preview Redis configuration
  AURUM_API_REDIS_URL: "redis://redis-preview.aurum-dev.svc.cluster.local:6379/0"
  # Preview Kafka configuration
  KAFKA_EXTERNAL_BOOTSTRAP: "kafka-preview.aurum-dev.svc.cluster.local:9092"
  # Preview Trino configuration
  AURUM_API_TRINO_HOST: "trino-preview.aurum-dev.svc.cluster.local"
  AURUM_API_TRINO_PORT: "8080"
  AURUM_API_TRINO_USER: "aurum"
  AURUM_API_TRINO_SCHEME: "http"
  # Preview Vault configuration
  VAULT_ADDR: "http://vault-preview.aurum-dev.svc.cluster.local:8200"
  VAULT_TOKEN_FILE: "/vault/token"
  # Preview monitoring configuration
  AURUM_OTEL_SERVICE_NAME: "aurum-preview"
  AURUM_OTEL_EXPORTER_ENDPOINT: "http://jaeger-preview.aurum-dev.svc.cluster.local:4317"
