apiVersion: v1
kind: ServiceAccount
metadata:
  name: aurum-external-collectors
  labels:
    app.kubernetes.io/name: aurum-external-collectors
    app.kubernetes.io/component: collectors
    app.kubernetes.io/part-of: aurum
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-run-as-init: "true"
    vault.hashicorp.com/role: external-data-role
    vault.hashicorp.com/agent-inject-secret-collectors-env: secret/data/aurum/eia
    vault.hashicorp.com/agent-inject-template-collectors-env: |
      {{- with secret "secret/data/aurum/eia" }}
      export EIA_API_KEY="{{ .Data.data.api_key | default "" }}"
      {{- end }}
      {{- with secret "secret/data/aurum/fred" }}
      export FRED_API_KEY="{{ .Data.data.api_key | default "" }}"
      {{- end }}
      {{- with secret "secret/data/aurum/noaa" }}
      export NOAA_GHCND_TOKEN="{{ .Data.data.token | default "" }}"
      {{- end }}
      {{- with secret "secret/data/aurum/pjm" }}
      export PJM_API_KEY="{{ .Data.data.token | default "" }}"
      {{- end }}
