apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurum-api-celery-worker
  namespace: aurum-dev
  labels:
    app.kubernetes.io/name: aurum-api-celery-worker
    app.kubernetes.io/component: celery-worker
    app.kubernetes.io/part-of: aurum
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aurum-api-celery-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aurum-api-celery-worker
        app.kubernetes.io/component: celery-worker
        app.kubernetes.io/part-of: aurum
    spec:
      serviceAccountName: aurum-api
      containers:
        - name: celery-worker
          image: aurum-api:latest
          imagePullPolicy: IfNotPresent
          command: ["celery", "-A", "aurum.api.celery_app", "worker", "--loglevel=info", "--concurrency=2", "--queues=default"]
          ports:
            - containerPort: 9464
              name: metrics
          envFrom:
            - configMapRef:
                name: aurum-api-config
            - secretRef:
                name: aurum-api-secrets
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AURUM_METRICS_DIR
              value: /tmp/aurum
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "pgrep -f 'celery.*worker' > /dev/null"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "pgrep -f 'celery.*worker' > /dev/null"]
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: aurum-api-celery-worker
  namespace: aurum-dev
  labels:
    app.kubernetes.io/name: aurum-api-celery-worker
    app.kubernetes.io/component: celery-worker
    app.kubernetes.io/part-of: aurum
spec:
  selector:
    app.kubernetes.io/name: aurum-api-celery-worker
  ports:
    - name: metrics
      port: 9464
      targetPort: 9464
      protocol: TCP
