apiVersion: v1
kind: ConfigMap
metadata:
  name: aurum-api-config
  labels:
    app.kubernetes.io/name: aurum-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: aurum
    app.kubernetes.io/managed-by: kustomize
data:
  AURUM_API_TRINO_HOST: trino.aurum-dev.svc.cluster.local
  AURUM_API_TRINO_PORT: "8080"
  AURUM_API_TRINO_USER: aurum
  AURUM_API_TRINO_SCHEME: http
  AURUM_API_REDIS_URL: redis://redis.aurum-dev.svc.cluster.local:6379/0
  AURUM_API_CACHE_TTL: "60"
  AURUM_API_ISO_LMP_CACHE_TTL: "60"
  AURUM_API_ISO_LMP_INMEM_TTL: "30"
  AURUM_API_RATE_LIMIT_RPS: "10"
  AURUM_API_RATE_LIMIT_BURST: "20"
  AURUM_API_CORS_ORIGINS: "*"
  AURUM_API_INMEMORY_TTL: "60"
  AURUM_API_GZIP_MIN_BYTES: "500"
  AURUM_API_SCENARIO_OUTPUTS_ENABLED: "1"
  AURUM_API_OIDC_ISSUER: ""
  AURUM_API_OIDC_AUDIENCE: ""
  AURUM_API_OIDC_JWKS_URL: ""
  AURUM_API_JWT_LEEWAY: "60"
  AURUM_API_AUTH_DISABLED: "0"
  AURUM_API_ADMIN_GROUP: aurum-admins
  # Fallback DSN without password; overridden by secret for real deployments
  AURUM_APP_DB_DSN: postgresql://aurum@postgres.aurum-dev.svc.cluster.local:5432/aurum
  KAFKA_EXTERNAL_BOOTSTRAP: kafka.aurum.localtest.me:31092
  SCHEMA_REGISTRY_EXTERNAL_URL: http://schema-registry.aurum.localtest.me
  AURUM_OTEL_SERVICE_NAME: aurum-api
  AURUM_OTEL_EXPORTER_ENDPOINT: http://jaeger-collector.aurum-dev.svc.cluster.local:4317
  AURUM_OTEL_EXPORTER_INSECURE: "true"
  AURUM_API_METRICS_ENABLED: "1"
  AURUM_API_METRICS_PATH: "/metrics"
  AURUM_ENABLE_MIGRATION_MONITORING: "0"
  AURUM_API_CONCURRENCY_ENABLED: "1"
  AURUM_API_CONCURRENCY_MAX_CONCURRENT_REQUESTS: "120"
  AURUM_API_CONCURRENCY_MAX_REQUESTS_PER_SECOND: "15"
  AURUM_API_CONCURRENCY_MAX_REQUEST_DURATION_SECONDS: "30"
  AURUM_API_CONCURRENCY_MAX_REQUESTS_PER_TENANT: "20"
  AURUM_API_CONCURRENCY_TENANT_BURST_LIMIT: "50"
  AURUM_API_CONCURRENCY_TENANT_QUEUE_LIMIT: "64"
  AURUM_API_CONCURRENCY_QUEUE_TIMEOUT_SECONDS: "2.0"
  AURUM_API_CONCURRENCY_BURST_REFILL_PER_SECOND: "0.5"
  AURUM_API_CONCURRENCY_SLOW_START_INITIAL_LIMIT: "2"
  AURUM_API_CONCURRENCY_SLOW_START_STEP_SECONDS: "3.0"
  AURUM_API_CONCURRENCY_SLOW_START_STEP_SIZE: "1"
  AURUM_API_CONCURRENCY_SLOW_START_COOLDOWN_SECONDS: "30.0"
  AURUM_API_CONCURRENCY_REDIS_ENABLED: "1"
  AURUM_API_CONCURRENCY_REDIS_URL: "redis://redis.aurum-dev.svc.cluster.local:6379/0"
  AURUM_API_CONCURRENCY_REDIS_NAMESPACE: "aurum:api:concurrency"
  AURUM_API_CONCURRENCY_REDIS_POLL_INTERVAL_SECONDS: "0.05"
  AURUM_API_CONCURRENCY_REDIS_QUEUE_STALE_SECONDS: "2.0"
  AURUM_API_CONCURRENCY_REDIS_QUEUE_TTL_SECONDS: "30.0"
  AURUM_API_CONCURRENCY_BACKPRESSURE_RATIO_THRESHOLD: "0"
  AURUM_API_CONCURRENCY_BACKPRESSURE_HEADER: "X-Backpressure"
  AURUM_API_OFFLOAD_ENABLED: "0"
  AURUM_API_OFFLOAD_USE_STUB: "1"
  AURUM_API_OFFLOAD_CELERY_BROKER_URL: "redis://redis.aurum-dev.svc.cluster.local:6379/0"
  AURUM_API_OFFLOAD_CELERY_RESULT_BACKEND: "redis://redis.aurum-dev.svc.cluster.local:6379/1"
  AURUM_API_OFFLOAD_DEFAULT_QUEUE: "default"
