apiVersion: v1
kind: ConfigMap
metadata:
  name: aurum-api-config
  labels:
    app.kubernetes.io/name: aurum-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: aurum
    app.kubernetes.io/managed-by: kustomize
data:
  AURUM_API_TRINO_HOST: trino.aurum-dev.svc.cluster.local
  AURUM_API_TRINO_PORT: "8080"
  AURUM_API_TRINO_USER: aurum
  AURUM_API_TRINO_SCHEME: http
  AURUM_API_REDIS_URL: redis://redis.aurum-dev.svc.cluster.local:6379/0
  AURUM_API_CACHE_TTL: "60"
  AURUM_API_RATE_LIMIT_RPS: "10"
  AURUM_API_RATE_LIMIT_BURST: "20"
  AURUM_API_CORS_ORIGINS: "*"
  AURUM_API_INMEMORY_TTL: "60"
  AURUM_API_GZIP_MIN_BYTES: "500"
  AURUM_API_SCENARIO_OUTPUTS_ENABLED: "1"
  AURUM_API_OIDC_ISSUER: ""
  AURUM_API_OIDC_AUDIENCE: ""
  AURUM_API_OIDC_JWKS_URL: ""
  AURUM_API_JWT_LEEWAY: "60"
  AURUM_API_AUTH_DISABLED: "0"
  AURUM_API_ADMIN_GROUP: aurum-admins
  # Fallback DSN without password; overridden by secret for real deployments
  AURUM_APP_DB_DSN: postgresql://aurum@postgres.aurum-dev.svc.cluster.local:5432/aurum
  KAFKA_EXTERNAL_BOOTSTRAP: kafka.aurum.localtest.me:31092
  SCHEMA_REGISTRY_EXTERNAL_URL: http://schema-registry.aurum.localtest.me
  AURUM_OTEL_SERVICE_NAME: aurum-api
  AURUM_OTEL_EXPORTER_ENDPOINT: http://jaeger-collector.aurum-dev.svc.cluster.local:4317
  AURUM_OTEL_EXPORTER_INSECURE: "true"
