apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurum-api
  labels:
    app.kubernetes.io/name: aurum-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: aurum
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aurum-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aurum-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: aurum
    spec:
      serviceAccountName: aurum-api
      containers:
        - name: api
          image: aurum-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: aurum-api-config
            - secretRef:
                name: aurum-api-secrets
          startupProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
