apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingressroute.yaml
  - pdb.yaml
  - networkpolicy.yaml
commonLabels:
  app.kubernetes.io/part-of: aurum
  app.kubernetes.io/component: api
