apiVersion: v1
kind: Secret
metadata:
  name: aurum-api-secrets
  labels:
    app.kubernetes.io/name: aurum-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: aurum
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  AURUM_API_OIDC_CLIENT_ID: changeme-client
  AURUM_API_OIDC_CLIENT_SECRET: changeme-secret
  AURUM_API_JWT_SECRET: change-me
  TRINO_PASSWORD: ""
  REDIS_PASSWORD: ""
  AURUM_APP_DB_DSN: postgresql://aurum:aurum@postgres.aurum-dev.svc.cluster.local:5432/aurum
