apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aurum-api
  labels:
    app.kubernetes.io/name: aurum-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: aurum
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aurum-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
