apiVersion: v1
kind: Service
metadata:
  name: {{ include "aurum-scenario-worker.fullname" . }}
  labels:
    {{- include "aurum-scenario-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "aurum-scenario-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
