version: 2

models:
  - name: int_curve_monthly
    description: Intermediate model filtering to monthly tenors and latest copies per ingest.
    tests:
      - unique_combination:
          combination_of_columns:
            - curve_key
            - tenor_label
            - asof_date
    columns:
      - name: curve_key
        tests:
          - relationships:
              to: ref('stg_curve_observation')
              field: curve_key
              to_field: curve_key
      - name: asof_date
        tests:
          - not_null
      - name: currency
        description: Currency propagated from the staging model.
      - name: per_unit
        description: Unit denominator propagated from the staging model.
  - name: int_curve_calendar
    description: Calendar strips derived by averaging monthly curves.
    tests:
      - unique_combination:
          combination_of_columns:
            - curve_key
            - tenor_label
            - asof_date
    columns:
      - name: curve_key
        tests:
          - relationships:
              to: ref('int_curve_monthly')
              field: curve_key
              to_field: curve_key
      - name: asof_date
        tests:
          - not_null
      - name: tenor_type
        tests:
          - accepted_values:
              values: ['CALENDAR']
      - name: mid
        tests:
          - not_null
  - name: int_curve_quarter
    description: Quarterly strips derived by averaging monthly curves.
    tests:
      - unique_combination:
          combination_of_columns:
            - curve_key
            - tenor_label
            - asof_date
    columns:
      - name: curve_key
        tests:
          - relationships:
              to: ref('int_curve_monthly')
              field: curve_key
              to_field: curve_key
      - name: asof_date
        tests:
          - not_null
      - name: tenor_type
        tests:
          - accepted_values:
              values: ['QUARTER']
      - name: mid
        tests:
          - not_null
  - name: int_eia_series_enriched
    description: Intermediate model normalizing currency and unit metadata for EIA series.
    tests:
      - unique_combination:
          combination_of_columns:
            - series_id
            - period
    columns:
      - name: series_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_eia_series')
              field: series_id
              to_field: series_id
      - name: value_converted
        description: Numeric value after applying any canonical conversion rules.
      - name: currency_normalized
        description: Currency resolved from canonical metadata or unit mappings.
      - name: unit_normalized
        description: Unit denominator resolved from canonical metadata or unit mappings.
