apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurum-api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurum-scenario-worker
spec:
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            cpu: 500m
            memory: 1.5Gi
          limits:
            cpu: 3
            memory: 3Gi
