version: 2

models:
  - name: publish_curve_observation
    description: Incremental publish step that materializes the canonical curve table from landing data.
    tests:
      - unique_combination:
          combination_of_columns:
            - curve_key
            - tenor_label
            - asof_date
    meta:
      notes: "Add data tests for measurement tolerance once Iceberg fixtures are available."
  - name: mart_curve_latest
    description: Business mart exposing the latest available curve per identity and tenor.
    tests:
      - unique_combination:
          combination_of_columns:
            - curve_key
            - tenor_label
    columns:
      - name: curve_key
        tests:
          - not_null
          - relationships:
              to: ref('int_curve_monthly')
              field: curve_key
              to_field: curve_key
      - name: tenor_type
        tests:
          - accepted_values:
              values: ['MONTHLY', 'QUARTER', 'SEASON', 'CALENDAR', 'STRIP', 'CUSTOM']
      - name: mid
        tests:
          - not_null
      - name: currency
        description: Currency associated with the curve mid price.
      - name: per_unit
        description: Unit denominator associated with the curve mid price.
  - name: mart_scenario_output
    description: Latest scenario outputs materialized as a Trino view.
    tests:
      - unique_combination:
          combination_of_columns:
            - tenant_id
            - scenario_id
            - run_id
            - metric
            - tenor_label
    columns:
      - name: scenario_id
        tests:
          - not_null
          - relationships:
              to: ref('mart_scenario_output')
              field: scenario_id
              to_field: scenario_id
          - relationships:
              to: ref('mart_scenario_output')
              field: scenario_id
              to_field: scenario_id
          - relationships:
              to: source('iceberg_market', 'scenario_output')
              field: scenario_id
              to_field: scenario_id
      - name: run_id
        description: Identifier of the scenario run that produced the output.
        tests:
          - not_null
      - name: tenant_id
        tests:
          - not_null
          - relationships:
              to: ref('tenant_catalog')
              field: tenant_id
              to_field: tenant_id
      - name: value
        tests:
          - not_null
      - name: metric_currency
        description: Currency code parsed from the metric unit metadata.
      - name: metric_unit_denominator
        description: Unit denominator parsed from the metric unit metadata (e.g., MWh).
  - name: mart_scenario_metric_latest
    description: Helper view exposing the latest value per scenario and metric.
    tests:
      - unique_combination:
          combination_of_columns:
            - tenant_id
            - scenario_id
            - metric
    columns:
      - name: scenario_id
        tests:
          - not_null
      - name: run_id
        description: Run identifier corresponding to the latest metric value.
        tests:
          - not_null
      - name: tenant_id
        tests:
          - not_null
      - name: metric
        tests:
          - not_null
      - name: latest_value
        description: Most recent value for the metric.
      - name: latest_asof_date
        description: As-of date associated with the latest metric value.
  - name: mart_ppa_valuation
    description: Persisted PPA valuation cashflows and summary metrics.
    tests:
      - unique_combination:
          combination_of_columns:
            - ppa_contract_id
            - scenario_id
            - metric
            - period_start
    columns:
      - name: ppa_contract_id
        tests:
          - not_null
      - name: scenario_id
        tests:
          - not_null
      - name: metric
        tests:
          - not_null
  - name: mart_eia_series_latest
    description: Latest observation per series identifier with normalized units and currency.
    tests:
      - unique_combination:
          combination_of_columns:
            - series_id
    columns:
      - name: series_id
        tests:
          - relationships:
              to: ref('int_eia_series_enriched')
              field: series_id
              to_field: series_id
      - name: value
        tests:
          - not_null
      - name: currency_normalized
        tests:
          - not_null
      - name: unit_normalized
        tests:
          - not_null
  - name: mart_eia_series_facets
    description: Distinct facet values (dataset, frequency, area, sector, units) for filtering APIs.
    columns:
      - name: dataset
        tests:
          - not_null
      - name: frequency
        tests:
          - not_null
          - accepted_values:
              values: ['ANNUAL', 'QUARTERLY', 'MONTHLY', 'WEEKLY', 'DAILY', 'HOURLY', 'OTHER']
  - name: mart_eia_series_units
    description: Lookup of raw units to normalized currency and unit denominators.
    tests:
      - unique:
          column_name: unit_raw
    columns:
      - name: unit_raw
        tests:
          - not_null
  - name: fct_drought_index
    description: Latest drought index value per series_id and valid_date with geography context.
    tests:
      - unique_combination:
          combination_of_columns:
            - series_id
            - valid_date
    columns:
      - name: series_id
        tests:
          - relationships:
              to: ref('stg_drought_index')
              field: series_id
              to_field: series_id
      - name: value
        tests:
          - not_null
      - name: region_type
        tests:
          - not_null
          - relationships:
              to: source('iceberg_ref', 'geographies')
              field: region_type
              to_field: region_type
      - name: region_id
        tests:
          - not_null
          - relationships:
              to: source('iceberg_ref', 'geographies')
              field: region_id
              to_field: region_id
  - name: fct_usdm_area
    description: Latest USDM severity fractions by geography.
    tests:
      - unique_combination:
          combination_of_columns:
            - region_type
            - region_id
            - valid_date
    columns:
      - name: d0_frac
        tests:
          - not_null
      - name: d4_frac
        description: Fraction of area under D4 severity (may be zero).
      - name: region_type
        tests:
          - not_null
      - name: region_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_usdm_area')
              field: region_id
              to_field: region_id
  - name: fct_vector_event
    description: Latest vector overlay per layer/event with geometry.
    tests:
      - unique_combination:
          combination_of_columns:
            - layer
            - event_id
    columns:
      - name: layer
        tests:
          - not_null
      - name: event_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_vector_event')
              field: event_id
              to_field: event_id
      - name: source_url
        tests:
          - not_null

exposures:
  - name: scenario_outputs_mart
    type: dashboard
    maturity: medium
    url: https://internal.aurum.local/dashboards/scenario
    depends_on:
      - ref('mart_scenario_output')
      - ref('mart_scenario_metric_latest')
    owner:
      name: Scenario Analytics
      email: analytics@aurum.local
  - name: iceberg_maintenance
    type: application
    maturity: low
    url: https://airflow.aurum.local/dag/iceberg_maintenance
    description: Scheduled job that expires Iceberg snapshots and compacts data files.
    depends_on:
      - source('iceberg_market', 'curve_observation')
      - source('iceberg_market', 'scenario_output')
    owner:
      name: Platform Operations
      email: platform@aurum.local
