{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aurum-api.fullname" . }}
  labels:
    {{- include "aurum-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "aurum-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: ingress
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        {{- if .Values.networkPolicy.allowExternal }}
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- else }}
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow traffic to required services
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: trino
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kafka
      ports:
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9093
    # Allow HTTPS outbound for external APIs
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Deny all other egress
    - to: []
      ports:
        - protocol: TCP
          port: 53
          endPort: 65535
  {{- end }}
{{- end }}
