{{- if and .Values.reforecastCron.enabled .Values.reforecastCron.auth.enabled .Values.reforecastCron.auth.secretName }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.reforecastCron.auth.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    metadata:
      name: {{ .Values.reforecastCron.auth.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
  encryptedData:
    {{ .Values.reforecastCron.auth.secretKey | default "token" }}: {{ .Values.reforecastCron.auth.encryptedToken | required "Set reforecastCron.auth.encryptedToken with kubeseal output" }}
{{- end }}


