apiVersion: v1
kind: Service
metadata:
  name: {{ include "aurum-api.fullname" . }}
  labels:
    {{- include "aurum-api.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "aurum-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
