apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: aurum-dev
  labels:
    app: hive-metastore
spec:
  type: ClusterIP
  selector:
    app: hive-metastore
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: aurum-dev
  labels:
    app: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: metastore
          image: bde2020/hive-metastore:2.3.0-postgresql
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9083
          env:
            - name: DB_DRIVER
              value: postgres
            - name: DB_HOST
              value: postgres.aurum-dev.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: metastore
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: aurum-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aurum-secrets
                  key: POSTGRES_PASSWORD
            - name: HIVE_METASTORE_PORT
              value: "9083"
            - name: INIT_DB
              value: "true"
          readinessProbe:
            tcpSocket:
              port: 9083
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9083
            initialDelaySeconds: 20
            periodSeconds: 20

