apiVersion: v1
kind: Secret
metadata:
  name: vault-root-token
  namespace: aurum-dev
  labels:
    app: vault
stringData:
  token: aurum-dev-root
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: aurum-dev
  labels:
    app: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: aurum-dev
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      containers:
        - name: vault
          image: hashicorp/vault:1.15.5
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -euo pipefail
              vault server -dev -dev-root-token-id="${VAULT_DEV_ROOT_TOKEN_ID}" -dev-listen-address=0.0.0.0:8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: vault-root-token
                  key: token
            - name: VAULT_LOG_LEVEL
              value: info
          ports:
            - containerPort: 8200
              name: http
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: aurum-dev
  labels:
    app: vault
spec:
  type: NodePort
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: http
      nodePort: 30200
