apiVersion: v1
kind: Service
metadata:
  name: aurum-api
  labels:
    app.kubernetes.io/name: aurum-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: aurum
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app.kubernetes.io/name: aurum-api
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
