version: 2

sources:
  - name: iceberg_raw
    description: Iceberg raw landing tables populated by ingestion jobs.
    schema: "{{ 'raw' if target.name != 'duckdb' else target.schema ~ '_raw' }}"
    freshness:
      warn_after: {count: 6, period: hour}
      error_after: {count: 12, period: hour}
    tables:
      - name: curve_landing
        description: Landing table written directly by ingestion jobs (includes quarantine reason).
        loaded_at_field: _ingest_ts
        columns:
          - name: curve_key
            tests:
              - not_null
          - name: quarantine_reason
            description: Reason assigned when a row fails validation.
  - name: iceberg_market
    description: Iceberg curated market tables.
    schema: "{{ 'market' if target.name != 'duckdb' else target.schema ~ '_market' }}"
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: curve_observation
        description: Canonical Iceberg table containing normalized vendor curve rows.
        loaded_at_field: _ingest_ts
        columns:
          - name: curve_key
            tests:
              - not_null
          - name: _ingest_ts
            tests:
              - not_null
      - name: curve_dead_letter
        description: Dead letter capture table for schema drift and ingestion failures.
        loaded_at_field: ingest_ts
        columns:
          - name: source
            tests:
              - not_null
          - name: ingest_ts
            tests:
              - not_null
      - name: curve_observation_quarantine
        description: Repository of quarantined rows awaiting remediation.
        loaded_at_field: _ingest_ts
        columns:
          - name: curve_key
            tests:
              - not_null
          - name: quarantine_reason
            tests:
              - not_null
      - name: scenario_output
        description: Scenario engine outputs appended by the worker and exposed via Iceberg.
        loaded_at_field: _ingest_ts
        columns:
          - name: scenario_id
            tests:
              - not_null
          - name: tenant_id
            tests:
              - not_null
          - name: run_id
            tests:
              - not_null
  - name: timescale_eia
    description: Timescale hypertables storing streaming EIA observations.
    database: "{{ 'timeseries' if target.name != 'duckdb' else (target.database if target.database else 'main') }}"
    schema: "{{ 'public' if target.name != 'duckdb' else target.schema ~ '_public' }}"
    freshness:
      warn_after: {count: 6, period: hour}
      error_after: {count: 12, period: hour}
    tables:
      - name: eia_series_timeseries
        description: Canonical Timescale hypertable populated by the SeaTunnel Kafka→Timescale job.
        loaded_at_field: ingest_ts
        columns:
          - name: tenant_id
            tests:
              - not_null
          - name: series_id
            tests:
              - not_null
          - name: period_start
            tests:
              - not_null
          - name: ingest_job_id
          - name: ingest_run_id
          - name: ingest_batch_id
  - name: timescale_fred
    description: Timescale hypertable storing FRED macroeconomic series observations.
    database: "{{ 'timeseries' if target.name != 'duckdb' else (target.database if target.database else 'main') }}"
    schema: "{{ 'public' if target.name != 'duckdb' else target.schema ~ '_public' }}"
    freshness:
      warn_after: {count: 6, period: hour}
      error_after: {count: 12, period: hour}
    tables:
      - name: fred_series_timeseries
        description: Canonical Timescale hypertable populated by the FRED SeaTunnel job.
        loaded_at_field: ingest_ts
        columns:
          - name: tenant_id
            tests:
              - not_null
          - name: series_id
            tests:
              - not_null
          - name: obs_date
            tests:
              - not_null
          - name: frequency
          - name: seasonal_adjustment
          - name: value
          - name: raw_value
          - name: units
          - name: title
          - name: notes
          - name: metadata
          - name: ingest_ts
            tests:
              - not_null
          - name: ingest_job_id
          - name: ingest_run_id
          - name: ingest_batch_id
  - name: timescale_cpi
    description: Timescale hypertable storing CPI series observations sourced from FRED.
    database: "{{ 'timeseries' if target.name != 'duckdb' else (target.database if target.database else 'main') }}"
    schema: "{{ 'public' if target.name != 'duckdb' else target.schema ~ '_public' }}"
    freshness:
      warn_after: {count: 6, period: hour}
      error_after: {count: 12, period: hour}
    tables:
      - name: cpi_series_timeseries
        description: CPI series staging table hydrated via Kafka → Timescale streaming job.
        loaded_at_field: ingest_ts
        columns:
          - name: tenant_id
            tests:
              - not_null
          - name: series_id
            tests:
              - not_null
          - name: period
            tests:
              - not_null
          - name: area
          - name: frequency
          - name: seasonal_adjustment
          - name: value
          - name: units
          - name: source
          - name: metadata
          - name: ingest_ts
            tests:
              - not_null
          - name: ingest_job_id
          - name: ingest_run_id
          - name: ingest_batch_id
  - name: timescale_noaa
    description: Timescale hypertable storing NOAA GHCND observations.
    database: "{{ 'timeseries' if target.name != 'duckdb' else (target.database if target.database else 'main') }}"
    schema: "{{ 'public' if target.name != 'duckdb' else target.schema ~ '_public' }}"
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: noaa_weather_timeseries
        description: Timescale sink populated from NOAA Kafka ingestion streams.
        loaded_at_field: ingest_ts
        columns:
          - name: tenant_id
            tests:
              - not_null
          - name: station_id
            tests:
              - not_null
          - name: observation_date
            tests:
              - not_null
          - name: element
            tests:
              - not_null
          - name: station_name
          - name: latitude
          - name: longitude
          - name: elevation_m
          - name: dataset
          - name: value
          - name: raw_value
          - name: unit
          - name: observation_time
          - name: measurement_flag
          - name: quality_flag
          - name: source_flag
          - name: attributes
          - name: ingest_ts
            tests:
              - not_null
          - name: ingest_job_id
          - name: ingest_run_id
          - name: ingest_batch_id
  - name: timescale_ops
    description: Operational metrics persisted to Timescale for platform observability.
    database: "{{ 'timeseries' if target.name != 'duckdb' else (target.database if target.database else 'main') }}"
    schema: "{{ 'public' if target.name != 'duckdb' else target.schema ~ '_public' }}"
    freshness:
      warn_after: {count: 30, period: minute}
      error_after: {count: 2, period: hour}
    tables:
      - name: ops_metrics
        description: Operational metrics stream emitted by workers and platform services.
        loaded_at_field: ts
        columns:
          - name: metric
            tests:
              - not_null
          - name: ts
            tests:
              - not_null
  - name: iceberg_environment
    description: Iceberg environment schema feeding drought analytics.
    schema: "{{ 'environment' if target.name != 'duckdb' else target.schema ~ '_environment' }}"
    freshness:
      warn_after: {count: 6, period: hour}
      error_after: {count: 12, period: hour}
    tables:
      - name: drought_index
        description: Zonal drought index measurements written from Airflow ingestion.
        loaded_at_field: ingest_ts
        columns:
          - name: series_id
            tests:
              - not_null
          - name: region_type
            tests:
              - not_null
          - name: region_id
            tests:
              - not_null
          - name: valid_date
            tests:
              - not_null
      - name: usdm_area
        description: USDM area fractions by severity and geography.
        loaded_at_field: ingest_ts
        columns:
          - name: region_type
            tests:
              - not_null
          - name: region_id
            tests:
              - not_null
          - name: valid_date
            tests:
              - not_null
      - name: vector_events
        description: Canonicalized vector overlay events (QPF, AHPS, AQI, wildfire, etc.).
        loaded_at_field: ingest_ts
        columns:
          - name: layer
            tests:
              - not_null
          - name: event_id
            tests:
              - not_null
  - name: iceberg_ref
    description: Reference geometries aligned to environment datasets.
    schema: "{{ 'ref' if target.name != 'duckdb' else target.schema ~ '_ref' }}"
    freshness:
      warn_after: {count: 1, period: day}
      error_after: {count: 2, period: day}
    tables:
      - name: geographies
        description: Reference geometries keyed by region_type and region_id.
        loaded_at_field: updated_at
        columns:
          - name: region_type
            tests:
              - not_null
          - name: region_id
            tests:
              - not_null
  - name: iceberg_external
    description: Iceberg external data schema for third-party time series and catalog data.
    schema: "{{ 'external' if target.name != 'duckdb' else target.schema ~ '_external' }}"
    freshness:
      warn_after: {count: 6, period: hour}
      error_after: {count: 12, period: hour}
    tables:
      - name: series_catalog
        description: External series catalog from upstream providers (FRED, EIA, etc.).
        loaded_at_field: _ingest_ts
        columns:
          - name: tenant_id
            tests:
              - not_null
          - name: provider
            tests:
              - not_null
          - name: series_id
            tests:
              - not_null
          - name: dataset_code
          - name: title
            tests:
              - not_null
          - name: unit_code
          - name: frequency_code
          - name: geo_id
          - name: start_ts
          - name: end_ts
          - name: last_observation_ts
          - name: asof_date
          - name: created_at
          - name: updated_at
          - name: ingest_ts
            tests:
              - not_null
          - name: ingest_job_id
          - name: ingest_run_id
          - name: ingest_batch_id
          - name: version
      - name: timeseries_observation
        description: External timeseries observations from upstream providers.
        loaded_at_field: _ingest_ts
        columns:
          - name: tenant_id
            tests:
              - not_null
          - name: provider
            tests:
              - not_null
          - name: series_id
            tests:
              - not_null
          - name: ts
            tests:
              - not_null
          - name: asof_date
            tests:
              - not_null
          - name: value
          - name: value_raw
          - name: unit_code
          - name: geo_id
          - name: dataset_code
          - name: frequency_code
          - name: status
          - name: quality_flag
          - name: source_event_id
          - name: ingest_ts
            tests:
              - not_null
          - name: ingest_job_id
          - name: ingest_run_id
          - name: ingest_batch_id
