apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: aurum-dev
  labels:
    app: grafana
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - uid: clickhouse
        name: ClickHouse
        type: grafana-clickhouse-datasource
        access: proxy
        url: http://clickhouse.aurum-dev.svc.cluster.local:8123
        isDefault: true
        jsonData:
          defaultDatabase: ops
          username: default
          tlsSkipVerify: true
        secureJsonData:
          password: ""
      - uid: prometheus
        name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.aurum-dev.svc.cluster.local:9090
        jsonData:
          httpMethod: GET
          manageAlerts: false
      - uid: aurum-postgres
        name: Postgres (Ops)
        type: postgres
        access: proxy
        url: postgres.aurum-dev.svc.cluster.local:5432
        user: aurum
        database: aurum
        jsonData:
          sslmode: disable
        secureJsonData:
          password: aurum
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
  namespace: aurum-dev
  labels:
    app: grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: Aurum
        folder: Aurum
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
