{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "aurum-api.fullname" . }}
  labels:
    {{- include "aurum-api.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "aurum-api.fullname" . }}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        mode: "Auto"
        minAllowed:
          cpu: 50m
          memory: 128Mi
        maxAllowed:
          cpu: "8"
          memory: 8Gi
        controlledResources: ["cpu", "memory"]
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "aurum-api.fullname" . }}-canary
  labels:
    {{- include "aurum-api.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "aurum-api.fullname" . }}-canary
  updatePolicy:
    updateMode: "Initial"
    evictionRequirements:
      - resources: ["cpu", "memory"]
        operators: ["In"]
        values: ["0.5", "0.5"]
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        mode: "Auto"
        minAllowed:
          cpu: 50m
          memory: 128Mi
        maxAllowed:
          cpu: "4"
          memory: 4Gi
        controlledResources: ["cpu", "memory"]
{{- end }}
