"""Shared schema definition for vendor curve parsers."""

CANONICAL_COLUMNS = [
    "asof_date",
    "source_file",
    "sheet_name",
    "asset_class",
    "region",
    "iso",
    "location",
    "market",
    "product",
    "block",
    "spark_location",
    "price_type",
    "units_raw",
    "currency",
    "per_unit",
    "tenor_type",
    "contract_month",
    "tenor_label",
    "value",
    "bid",
    "ask",
    "mid",
    "curve_key",
    "version_hash",
    "_ingest_ts",
]
