apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurum-api
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: AURUM_API_AUTH_DISABLED
              value: "1"
            - name: AURUM_API_RATE_LIMIT_ENABLED
              value: "0"
            - name: AURUM_TELEMETRY_SERVICE_NAME
              value: "aurum-api-dev"
            - name: AURUM_API_GZIP_MIN_BYTES
              value: "1000"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "aurum"
            - name: POSTGRES_USER
              value: "aurum"
            - name: POSTGRES_PASSWORD
              value: "aurum123"
            - name: TRINO_HOST
              value: "trino"
            - name: TRINO_PORT
              value: "8080"
            - name: TRINO_USER
              value: "aurum"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "aurum123"
          command:
            - uvicorn
          args:
            - aurum.api.app:app
            - --host
            - "0.0.0.0"
            - --port
            - "8080"
