apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurum-api
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-run-as-init: "true"
        vault.hashicorp.com/role: aurum-api
        vault.hashicorp.com/agent-inject-secret-api-env: secret/data/aurum/dev/api
        vault.hashicorp.com/agent-inject-template-api-env: |-
          {{- with secret "secret/data/aurum/dev/api" -}}
          {{- range $k, $v := .Data.data }}
          {{ $k }}={{ $v }}
          {{- end }}
          {{- end }}
    spec:
      containers:
        - name: api
          command:
            - /bin/sh
          args:
            - -c
            - |
              set -a
              . /vault/secrets/api-env
              set +a
              exec uvicorn aurum.api.app:app --host 0.0.0.0 --port 8080
