coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
query.max-memory=5GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
query.client.timeout=2m
exchange.client-threads=25
exchange.max-response-size=32MB
exchange.http-client.max-connections=500
exchange.http-client.max-connections-per-address=32
query.min-scheduling-eligible-drivers=32
query.remote-task.max-callback-threads=16
query.remote-task.allow-concurrent-exchange=false
optimizer.optimize-hash-generation=true
optimizer.optimize-metadata-queries=true
optimizer.use-legacy-scheduler=false
optimizer.allow-merge-union=true
optimizer.join-reordering-strategy=AUTOMATIC
optimizer.enable-stats-calculator=true
optimizer.join-multi-clause-enabled=true
optimizer.single-distinct-aggregation=true
optimizer.index-joins-enabled=true
query.execution-policy=adaptive
exchange.hash-partition-count=32
spill-enabled=true
orc.max-buffer-size=256MB
orc.stream-buffer-size=16MB
orc.writer.max-stripe-rows=1000000
orc.writer.max-stripe-size=128MB
