version: 2
models:
- name: mart_external__geo
  description: Canonical geography dimension for external data providers.
  tests:
  - unique_combination:
      combination_of_columns:
      - provider
      - provider_geo_code
  columns:
  - name: geo_key
    tests:
    - not_null
    - unique
  - name: provider
    tests:
    - not_null
  - name: provider_geo_code
    tests:
    - not_null
  - name: state_code
    description: Canonical state code (ISO 3166-2)
  - name: country_code
    description: Canonical country code (ISO 3166-1 alpha-2)
    tests:
    - not_null
  - name: zone_name
    description: Provider-specific zone or region name
  - name: geography_type
    description: Type of geography (ISO_ZONE, PROVINCE, etc.)
  - name: canonical_region_id
    description: Reference to canonical geographies table
  - name: canonical_region_name
    description: Human readable name from canonical geographies
  - name: mapping_status
    description: Whether the geo code was successfully mapped to canonical geographies
    tests:
    - accepted_values:
        values:
        - MAPPED
        - UNMAPPED
- name: cur_external__obs_mapped
  description: Curated external observations transformed to match curve_observation
    format.
  tests:
  - unique_combination:
      combination_of_columns:
      - curve_key
      - tenor_label
      - asof_date
  columns:
  - name: asof_date
    tests:
    - not_null
  - name: curve_key
    tests:
    - not_null
  - name: mid
    description: Standardized value in USD/MWh
  - name: asset_class
    tests:
    - not_null
  - name: iso
    tests:
    - not_null
  - name: market
    tests:
    - not_null
  - name: product
    tests:
    - not_null
  - name: tenor_type
    tests:
    - not_null
  - name: _ingest_ts
    tests:
    - not_null
  - name: lineage_tags
    description: Data lineage tracking information
  
- name: mart_external_series_catalog
  description: Enriched external series catalog with canonical geography metadata.
  tests:
  - unique:
      column_name: series_catalog_sk
  columns:
  - name: tenant_id
    tests:
    - not_null
  - name: provider
    tests:
    - not_null
  - name: series_id
    tests:
    - not_null
  - name: series_catalog_sk
    description: Deterministic hash key for provider+series combination
    tests:
    - not_null
    - unique
  - name: canonical_region_id
    description: Reference to canonical geography when mapped
  - name: mapping_status
    tests:
    - accepted_values:
        values:
        - MAPPED
        - UNMAPPED
        - PARTIAL
  - name: iso_code
    description: Canonical ISO code (e.g., PJM, ISO-NE)
    tests:
    - not_null
  - name: iso_market
    description: Market designation (DA, RT, etc.) with UNKNOWN fallback when unmapped
    tests:
    - accepted_values:
        values:
        - DA
        - RT
        - DAM
        - RTM
        - UNKNOWN
  - name: iso_product
    description: Canonical product identifier (LMP, LOAD, GENERATION, etc.)
    tests:
    - not_null
  - name: iso_location_type
    description: Normalized ISO location type (NODE, ZONE, HUB, etc.)
    tests:
    - not_null
  - name: iso_location_name
    description: Human-readable ISO location name
  - name: iso_location_id
    description: Primary ISO location identifier aligned with provider geo id
    tests:
    - not_null
  - name: iso_timezone
    description: Canonical timezone for the series (IANA identifier)
    tests:
    - not_null
  - name: iso_interval_minutes
    description: Cadence of observations expressed in minutes
    tests:
    - not_null
  - name: iso_unit
    description: Canonical measurement unit (normalized to uppercase)
    tests:
    - not_null
  - name: iso_subject
    description: Subject classification used for aggregation and contracts
    tests:
    - not_null
  - name: iso_curve_role
    description: Contract role describing how the series is consumed (pricing, load, etc.)
    tests:
    - not_null
