apiVersion: v1
kind: Secret
metadata:
  name: aurum-external-collectors-secrets
  labels:
    app.kubernetes.io/name: aurum-external-collectors
    app.kubernetes.io/component: collectors
    app.kubernetes.io/part-of: aurum
type: Opaque
stringData:
  README: "Provisioned from Vault by injector; left intentionally empty."
