apiVersion: v1
kind: ServiceAccount
metadata:
  name: aurum-external-collectors
  labels:
    app.kubernetes.io/name: aurum-external-collectors
    app.kubernetes.io/component: collectors
    app.kubernetes.io/part-of: aurum
