apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
commonLabels:
  app.kubernetes.io/part-of: aurum
  app.kubernetes.io/component: scenario-worker
