apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aurum-scenario-worker
  labels:
    app.kubernetes.io/name: aurum-scenario-worker
    app.kubernetes.io/component: scenario-worker
    app.kubernetes.io/part-of: aurum
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aurum-scenario-worker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
