apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: aurum-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-job-runner
  namespace: aurum-dev
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-job-runner-binding
  namespace: aurum-dev
subjects:
  - kind: ServiceAccount
    name: airflow
    namespace: aurum-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-job-runner


