apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: aurum-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-job-runner
  namespace: aurum-dev
rules:
  - apiGroups: ["batch", "extensions", "apps"]
    resources: ["jobs", "deployments", "pods", "pods/log", "pods/exec", "services"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-job-runner-binding
  namespace: aurum-dev
subjects:
  - kind: ServiceAccount
    name: airflow
    namespace: aurum-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-job-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow-cluster-role
rules:
  - apiGroups: [""]
    resources: ["namespaces", "nodes", "persistentvolumes", "storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: airflow
    namespace: aurum-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: airflow-cluster-role


