apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: aurum-kafka
  namespace: aurum-dev
spec:
  kafka:
    version: 3.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          brokers:
            - broker: 0
              advertisedHost: kafka.aurum.localtest.me
              advertisedPort: 31092
              nodePort: 31092
    config:
      process.roles: broker,controller
      node.id: 0
      controller.listener.names: CONTROLLER
      inter.broker.listener.name: REPLICATION
      controller.quorum.voters: "0@aurum-kafka-kafka-0.aurum-kafka-kafka-brokers.aurum-dev.svc:9093"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    storage:
      type: ephemeral
  kafkaExporter:
    topicRegex: ".*"
  entityOperator:
    topicOperator: {}
    userOperator: {}
