apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: aurum-platform-alerts
  namespace: aurum-dev
  labels:
    app.kubernetes.io/name: aurum-platform-alerts
    app.kubernetes.io/part-of: aurum
spec:
  groups:
    - name: aurum-api
      rules:
        - alert: AurumApiHighErrorRate
          expr: |
            sum(rate(aurum_api_requests_total{status=~"5.."}[5m]))
              /
            clamp_min(sum(rate(aurum_api_requests_total[5m])), 1) > 0.05
          for: 5m
          labels:
            severity: critical
            service: api
          annotations:
            summary: "API 5xx rate above 5%"
            description: "More than 5% of requests returned 5xx in the last 5 minutes"
            runbook: "docs/runbooks/api.md#elevated-5xx"
        - alert: AurumApiLatencyP95Degraded
          expr: |
            histogram_quantile(
              0.95,
              sum(rate(aurum_api_request_duration_seconds_bucket[5m])) by (le)
            ) > 0.75
          for: 10m
          labels:
            severity: warning
            service: api
          annotations:
            summary: "API p95 latency degraded"
            description: "The 95th percentile latency exceeded 750ms for 10 minutes"
            runbook: "docs/runbooks/api.md#latency-spikes"
    - name: aurum-scenarios
      rules:
        - alert: AurumScenarioWorkerBacklog
          expr: |
            max_over_time(aurum_scenario_queue_size[10m]) > 0
              and sum(rate(aurum_scenario_requests_success_total[10m])) < 0.1
          for: 10m
          labels:
            severity: critical
            service: scenario-worker
          annotations:
            summary: "Scenario worker appears stuck"
            description: "Queue backlog persisted for 10m with no successful completions"
            runbook: "docs/runbooks/scenario-worker.md#stuck-runs"
        - alert: AurumScenarioRetriesExhausted
          expr: rate(aurum_scenario_retry_exhausted_total[10m]) > 0.05
          for: 5m
          labels:
            severity: warning
            service: scenario-worker
          annotations:
            summary: "Scenario retries exhausted"
            description: "More than 0.05 exhausted retries/sec over 5 minutes"
            runbook: "docs/runbooks/scenario-worker.md#retries"
    - name: aurum-airflow
      rules:
        - alert: AurumDagFailuresSpike
          expr: increase(airflow_dag_run_status{state="failed"}[15m]) > 3
          for: 15m
          labels:
            severity: critical
            service: airflow
          annotations:
            summary: "Airflow DAG failures detected"
            description: "More than three DAG runs failed in the last 15 minutes"
            runbook: "docs/runbooks/airflow.md#dag-failures"
        - alert: AurumDagSchedulerHeartbeatMissing
          expr: time() - airflow_scheduler_heartbeat_seconds > 300
          for: 5m
          labels:
            severity: critical
            service: airflow
          annotations:
            summary: "Airflow scheduler heartbeat missing"
            description: "Airflow scheduler has not emitted a heartbeat for >5 minutes"
            runbook: "docs/runbooks/airflow.md#scheduler-down"
    - name: aurum-data-quality
      rules:
        - alert: AurumDataStale
          expr: |
            max(aurum_watermark_age_seconds{source!=""}) > 7200
          for: 15m
          labels:
            severity: critical
            service: ingestion
          annotations:
            summary: "Ingestion watermark stale"
            description: "At least one ingestion source watermark is more than 2 hours old"
            runbook: "docs/runbooks/ingestion.md#staleness"
        - alert: AurumDataStaleWarning
          expr: |
            max(aurum_watermark_age_seconds{source!=""}) > 3600
          for: 30m
          labels:
            severity: warning
            service: ingestion
          annotations:
            summary: "Ingestion watermark approaching SLA"
            description: "At least one ingestion watermark exceeds 1 hour"
            runbook: "docs/runbooks/ingestion.md#staleness"
    - name: aurum-external-data
      rules:
        - alert: AurumExternalDataFreshnessSLOViolation
          expr: |
            max(aurum_external_data_freshness_seconds{provider!=""}) > 86400
          for: 15m
          labels:
            severity: critical
            service: external-data
          annotations:
            summary: "External data freshness SLO violation"
            description: "External data provider freshness exceeds 24 hours"
            runbook: "docs/runbooks/external-data.md#freshness-slo"
        - alert: AurumExternalDataFreshnessWarning
          expr: |
            max(aurum_external_data_freshness_seconds{provider!=""}) > 43200
          for: 30m
          labels:
            severity: warning
            service: external-data
          annotations:
            summary: "External data freshness approaching SLO"
            description: "External data provider freshness exceeds 12 hours"
            runbook: "docs/runbooks/external-data.md#freshness-slo"
        - alert: AurumExternalDataIngestionFailures
          expr: |
            sum(rate(aurum_external_ingestion_failures_total[15m])) > 0
          for: 5m
          labels:
            severity: warning
            service: external-data
          annotations:
            summary: "External data ingestion failures detected"
            description: "External data ingestion has failed in the last 15 minutes"
            runbook: "docs/runbooks/external-data.md#ingestion-failures"
        - alert: AurumExternalDataGEValidationFailures
          expr: |
            sum(rate(aurum_external_ge_validation_failures_total[10m])) > 0
          for: 5m
          labels:
            severity: critical
            service: external-data
          annotations:
            summary: "Great Expectations validation failures"
            description: "External data failed Great Expectations validation"
            runbook: "docs/runbooks/external-data.md#ge-failures"
        - alert: AurumExternalDataMappingCoverageLow
          expr: |
            sum(aurum_external_series_mapped_total) / sum(aurum_external_series_total) < 0.8
          for: 1h
          labels:
            severity: warning
            service: external-data
          annotations:
            summary: "External data mapping coverage below threshold"
            description: "Less than 80% of external series are mapped to curves"
            runbook: "docs/runbooks/external-data.md#mapping-coverage"
        - alert: AurumExternalDataQualityDegraded
          expr: |
            avg(aurum_external_data_quality_score) < 0.9
          for: 30m
          labels:
            severity: warning
            service: external-data
          annotations:
            summary: "External data quality degraded"
            description: "Overall external data quality score below 0.9 for 30 minutes"
            runbook: "docs/runbooks/external-data.md#quality-degradation"
    - name: aurum-slo
      rules:
        - alert: AurumApiAvailabilitySLOViolation
          expr: |
            1 - (sum(rate(aurum_api_requests_total{status=~"5.."}[15m]))
                 /
                 clamp_min(sum(rate(aurum_api_requests_total[15m])), 1)) < 0.999
          for: 15m
          labels:
            severity: critical
            slo: api_availability_99.9
          annotations:
            summary: "API availability SLO violation (99.9%)"
            description: "API availability dropped below 99.9% for 15 minutes"
            runbook: "docs/runbooks/slo.md#api-availability"
        - alert: AurumApiAvailabilitySLOWarning
          expr: |
            1 - (sum(rate(aurum_api_requests_total{status=~"5.."}[5m]))
                 /
                 clamp_min(sum(rate(aurum_api_requests_total[5m])), 1)) < 0.9995
          for: 5m
          labels:
            severity: warning
            slo: api_availability_99.95
          annotations:
            summary: "API availability SLO warning (99.95%)"
            description: "API availability dropped below 99.95% for 5 minutes"
            runbook: "docs/runbooks/slo.md#api-availability"
        - alert: AurumWorkerSuccessRateSLOViolation
          expr: |
            1 - (sum(rate(aurum_worker_errors_total[15m]))
                 /
                 clamp_min(sum(rate(aurum_worker_task_duration_seconds_count[15m])), 1)) < 0.99
          for: 15m
          labels:
            severity: critical
            slo: worker_success_rate_99
          annotations:
            summary: "Worker success rate SLO violation (99%)"
            description: "Worker success rate dropped below 99% for 15 minutes"
            runbook: "docs/runbooks/slo.md#worker-success-rate"
        - alert: AurumWorkerSuccessRateSLOWarning
          expr: |
            1 - (sum(rate(aurum_worker_errors_total[5m]))
                 /
                 clamp_min(sum(rate(aurum_worker_task_duration_seconds_count[5m])), 1)) < 0.995
          for: 5m
          labels:
            severity: warning
            slo: worker_success_rate_99.5
          annotations:
            summary: "Worker success rate SLO warning (99.5%)"
            description: "Worker success rate dropped below 99.5% for 5 minutes"
            runbook: "docs/runbooks/slo.md#worker-success-rate"
        - alert: AurumCacheHitRateSLOViolation
          expr: |
            sum(rate(aurum_cache_hits_total[15m]))
            /
            clamp_min(sum(rate(aurum_cache_operations_total[15m])), 1) < 0.8
          for: 15m
          labels:
            severity: critical
            slo: cache_hit_rate_80
          annotations:
            summary: "Cache hit rate SLO violation (80%)"
            description: "Cache hit rate dropped below 80% for 15 minutes"
            runbook: "docs/runbooks/slo.md#cache-hit-rate"
        - alert: AurumCacheHitRateSLOWarning
          expr: |
            sum(rate(aurum_cache_hits_total[5m]))
            /
            clamp_min(sum(rate(aurum_cache_operations_total[5m])), 1) < 0.9
          for: 5m
          labels:
            severity: warning
            slo: cache_hit_rate_90
          annotations:
            summary: "Cache hit rate SLO warning (90%)"
            description: "Cache hit rate dropped below 90% for 5 minutes"
            runbook: "docs/runbooks/slo.md#cache-hit-rate"
        - alert: AurumIngestionBacklogSLOViolation
          expr: |
            sum(aurum_ingestion_backlog) > 10000
          for: 30m
          labels:
            severity: critical
            slo: ingestion_backlog_10000
          annotations:
            summary: "Ingestion backlog SLO violation (>10k records)"
            description: "Ingestion backlog exceeded 10,000 records for 30 minutes"
            runbook: "docs/runbooks/slo.md#ingestion-backlog"
        - alert: AurumIngestionBacklogSLOWarning
          expr: |
            sum(aurum_ingestion_backlog) > 5000
          for: 15m
          labels:
            severity: warning
            slo: ingestion_backlog_5000
          annotations:
            summary: "Ingestion backlog SLO warning (>5k records)"
            description: "Ingestion backlog exceeded 5,000 records for 15 minutes"
            runbook: "docs/runbooks/slo.md#ingestion-backlog"
        - alert: AurumRateLimitViolationsSLOViolation
          expr: |
            sum(rate(aurum_rate_limit_rejected_total[15m])) > 1.0
          for: 10m
          labels:
            severity: critical
            slo: rate_limit_violations_1_per_sec
          annotations:
            summary: "Rate limit violations SLO violation (>1/sec)"
            description: "Rate limit violations exceeded 1 per second for 10 minutes"
            runbook: "docs/runbooks/slo.md#rate-limit-violations"
        - alert: AurumRateLimitViolationsSLOWarning
          expr: |
            sum(rate(aurum_rate_limit_rejected_total[5m])) > 0.1
          for: 5m
          labels:
            severity: warning
            slo: rate_limit_violations_0.1_per_sec
          annotations:
            summary: "Rate limit violations SLO warning (>0.1/sec)"
            description: "Rate limit violations exceeded 0.1 per second for 5 minutes"
            runbook: "docs/runbooks/slo.md#rate-limit-violations"
        - alert: AurumDatabaseConnectionPoolExhaustion
          expr: |
            sum(aurum_db_connections_active) / sum(aurum_db_connections_total) > 0.9
          for: 10m
          labels:
            severity: critical
            slo: db_connection_pool_90
          annotations:
            summary: "Database connection pool near exhaustion (>90%)"
            description: "Database connection pool utilization exceeded 90% for 10 minutes"
            runbook: "docs/runbooks/slo.md#db-connection-pool"
        - alert: AurumDatabaseConnectionPoolWarning
          expr: |
            sum(aurum_db_connections_active) / sum(aurum_db_connections_total) > 0.8
          for: 15m
          labels:
            severity: warning
            slo: db_connection_pool_80
          annotations:
            summary: "Database connection pool high utilization (>80%)"
            description: "Database connection pool utilization exceeded 80% for 15 minutes"
            runbook: "docs/runbooks/slo.md#db-connection-pool"
