apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: aurum-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.io
      - traefik.containo.us
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - middlewaretcps
      - tlsoptions
      - tlsstores
      - traefikservices
      - serverstransports
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: aurum-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: aurum-dev
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik
      volumes:
        - name: acme-data
          emptyDir: {}
      containers:
        - name: traefik
          image: traefik:v2.10
          args:
            - --api.dashboard=true
            - --api.insecure=true
            - --entrypoints.web.address=:32080
            - --entrypoints.web.forwardedHeaders.insecure=true
            - --entrypoints.websecure.address=:32443
            - --entrypoints.websecure.forwardedHeaders.insecure=true
            - --entrypoints.websecure.http.tls=true
            - --providers.kubernetescrd
            - --providers.kubernetesingress
            - --providers.kubernetesingress.ingressendpoint.publishedservice=aurum-dev/traefik
            - --accesslog=true
            - --log.level=INFO
            - --ping=true
            - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
            - --certificatesresolvers.letsencrypt.acme.email=admin@aurum.localtest.me
            - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
          volumeMounts:
            - name: acme-data
              mountPath: /data
          ports:
            - name: web
              containerPort: 32080
            - name: websecure
              containerPort: 32443
            - name: admin
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /ping
              port: admin
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: admin
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: aurum-dev
spec:
  type: NodePort
  selector:
    app: traefik
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 32080
    - name: websecure
      port: 443
      targetPort: websecure
      nodePort: 32443
    - name: admin
      port: 9000
      targetPort: admin
      nodePort: 32090
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: aurum-dev
spec:
  type: ClusterIP
  selector:
    app: traefik
  ports:
    - name: http
      port: 9000
      targetPort: admin
