apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurum-scenario-worker
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-run-as-init: "true"
        vault.hashicorp.com/role: aurum-scenario-worker
        vault.hashicorp.com/agent-inject-secret-worker-env: secret/data/aurum/ci/scenario-worker
        vault.hashicorp.com/agent-inject-template-worker-env: |-
          {{- with secret "secret/data/aurum/ci/scenario-worker" -}}
          {{- range $k, $v := .Data.data }}
          {{ $k }}={{ $v }}
          {{- end }}
          {{- end }}
    spec:
      containers:
        - name: worker
          command:
            - /bin/sh
          args:
            - -c
            - |
              set -a
              . /vault/secrets/worker-env
              set +a
              exec python -m aurum.scenarios.worker
