name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Ruff lint
        run: make lint
      - name: Pytest
        run: make test

  scenario-smoke:
    name: Scenario Smoke
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image for smoke test
        run: |
          docker build \
            --file Dockerfile.api \
            --tag aurum-api:local \
            .

      - name: Run scenario smoke test
        env:
          COMPOSE_PROFILES: worker
        run: |
          bash scripts/ci/scenario_smoke.sh

  build-and-publish:
    name: Build & Publish Images
    needs: lint-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: |
            ghcr.io/aurum/aurum-api:dev
            ghcr.io/aurum/aurum-api:${{ github.sha }}

      - name: Build & push worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.worker
          push: true
          tags: |
            ghcr.io/aurum/aurum-worker:dev
            ghcr.io/aurum/aurum-worker:${{ github.sha }}

      - name: Generate kustomize overlay
        run: |
          mkdir -p dist/kustomize/dev-${GITHUB_SHA}
          cat <<PATCH > dist/kustomize/dev-${GITHUB_SHA}/kustomization.yaml
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          namespace: aurum-dev
          resources:
            - ../../k8s/dev
          images:
            - name: ghcr.io/aurum/aurum-api
              newTag: ${GITHUB_SHA}
            - name: ghcr.io/aurum/aurum-worker
              newTag: ${GITHUB_SHA}
          PATCH
      - name: Upload kustomize overlay
        uses: actions/upload-artifact@v4
        with:
          name: kustomize-images-${{ github.sha }}
          path: dist/kustomize/dev-${{ github.sha }}
