name: Publish Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'openapi/**'
      - 'scripts/docs/**'
      - 'Makefile'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Build docs
        run: |
          make docs-build

      - name: Prepare site
        run: |
          mkdir -p site
          cp -r docs/* site/
          # Provide a simple index
          echo "<html><head><meta charset=\"utf-8\"><title>Aurum Docs</title></head><body><h1>Aurum Documentation</h1><ul>" > site/index.html
          for f in $(ls -1 site | sort); do echo "<li><a href=\"$f\">$f</a></li>" >> site/index.html; done
          echo "</ul></body></html>" >> site/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          force_orphan: true

